trigger: none
resources:
  repositories:
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
jobs:
  - template: ../../../eng/pipelines/templates/jobs/archetype-sdk-integration.yml
    parameters:
      PackageName: "@azure/ai-form-recognizer"
      ResourceServiceDirectory: formrecognizer
      EnvVars:
        AZURE_CLIENT_ID: $(aad-azure-sdk-test-client-id)
        AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id)
        AZURE_CLIENT_SECRET: $(aad-azure-sdk-test-client-secret)

      Matrix:
        Linux Node 8:
          OSVmImage: "ubuntu-18.04"
          TestType: "node"
          NodeVersion: "8.x"
      PreSteps:
        - bash: |
            echo "ping -c 5 -4 `echo $AZURE_FORM_RECOGNIZER_ENDPOINT | awk -F/ '{print $3}'`"
            ping -c 5 -4 `echo $AZURE_FORM_RECOGNIZER_ENDPOINT | awk -F/ '{print $3}'`
          displayName: ping
        - bash: |
            echo "ping -c 5 -4 `echo $AZURE_FORM_RECOGNIZER_ENDPOINT | awk -F/ '{print $3}'`"
            ping -c 5 -4 `echo $AZURE_FORM_RECOGNIZER_ENDPOINT | awk -F/ '{print $3}'`
          displayName: nslookup
